# Generated by Django 2.1.7 on 2019-03-06 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190307_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='portfolio.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
